config/routes.rb
Rails.application.routes.draw do
  
  root 'projects#index'
  
  resources :static_pages, only: [:create]
  get 'legal', to: 'static_pages#legal_mentions'
  get 'donation', to: 'static_pages#donation'
  get 'about', to: 'static_pages#about'

  devise_for :users, :path => "/Mon_Profil"

  resources :users, except: [:new, :index, :create], path: "/Profil"
  resources :projects, :path => "/Projets" do
    resources :feats, except: [:index] ,:path => "/Feats"
  end
  resources :attachments, only: [:destroy]
  resources :likes, only: [:update]

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end

  namespace :admin do
    root to: 'static_pages#index'
    resources :users, except: [:new, :create]
    resources :projects, except: [:new, :create] do
      resources :feats, only: [:update, :destroy, :index]
    end
    resources :skills, except: [:show]
  end

end

app/models/skill.rb
class Skill < ApplicationRecord
  has_and_belongs_to_many :users
  has_and_belongs_to_many :projects
  validates :name,
    presence: true,
    length: { in: 3..25 },
    uniqueness: true
end

app/controllers/admin/skills_controller.rb
module Admin
  class SkillsController < ApplicationController
    before_action :set_skill, only: [:edit, :destroy, :update]

    def index
      @skills = Skill.all
    end

    def new
      @skill = Skill.new
    end

    def create
      @skill = Skill.new(skill_params)
      if @skill.save
        flash[:success] = "La compétence a bien été crée !"
        redirect_to admin_skills_path
      else
        flash[:warning] = "Il y eu un problème lors de la création de la compétence."
        render 'new'
      end
    end

    def edit
    end

    def update
      if @skill.update_attributes(skill_params)
        flash[:success] = "La compétence a bien été édité"
        redirect_to admin_skills_path
      else
        flash[:warning] = "Il y a eu un problème lors de la modification de la compétence."
        render 'edit'
      end
    end

    def destroy
      if @skill.destroy
        flash[:success] = 'La compétence a bien été supprimée.'
        redirect_to admin_skills_path
      else
        flash[:warning] = 'Il y a eu un problème lors de la suppression de la compétence.'
        redirect_to admin_skills_path
      end
    end

    private

    def skill_params
      params.require(:skill).permit(:name)
    end

    def set_skill
      @skill = Skill.find(params[:id])
    end
  end
end

app/views/admin/skills/_form.html.erb
<%= form_for ([:admin, @skill]) do |f| %>

<div class="card text-center" style="width: 22rem;">
    <div class="card-body">
    <%= label_tag 'Titre' %><br />
    <%= f.text_field :name %><br />

    <button type="submit" class="btn btn-primary mt-3">Envoyer</button>

    </div>
</div>
<% end %>

app/views/admin/skills/edit.html.erb
<% if @skill.errors.any? %>
<%= render "shared/error_messages", object: @skill %>
<% end %>

<div class="container">
  <h2>Modification</h2>
  <%= link_to 'Accueil Admin', admin_root_path, class: 'btn btn-info mb-1' %>
  <%= link_to 'Retour', admin_skills_path, class: 'btn btn-info mb-1' %>
  <%= render "form" %>
</div>

app/views/admin/skills/index.html.erb
<div class="container">
  <h2>Compétences en base de donnée</h2>
  <div><%= link_to 'Accueil Admin', admin_root_path, class: 'btn btn-info mb-1' %>
  <%= link_to '+ Ajouter une compétence', new_admin_skill_path, class: 'btn btn-info mb-1' %>
  </div>

  <table class="table table-hover table-sm bg-white">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Compétence</th>
        <th scope="col">Affectations sur projets</th>
        <th scope="col">Affectations sur utilisateurs</th>
      </tr>
    </thead>
    <tbody>
      <% @skills.each do |skill| %>
        <tr>
          <th><%= skill.id %></th>
          <th><%= skill.name %></th>
          <th><%= skill.projects.count %></th>
          <th><%= skill.users.count %></th>
          <th><%= link_to 'Afficher/Editer', edit_admin_skill_path(skill), class: 'btn btn-secondary btn-sm' %></th>
          <th><%= link_to 'Supprimer', admin_skill_path(skill), data: { method: :delete, confirm: "Est tu sûr de vouloir supprimer cette compétence ?" }, class: 'btn btn-danger btn-sm'%></th>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/skills/new.html.erb
<div class="container">
  <h2>Ajout d'une compétence</h2>
  <%= link_to 'Accueil Admin', admin_root_path, class: 'btn btn-info mb-1' %>
  <%= link_to 'Retour', admin_skills_path, class: 'btn btn-info mb-1' %>
  <%= render "form" %>
</div>