config/routes.rb
Rails.application.routes.draw do
  
  root 'projects#index'
  
  resources :static_pages, only: [:create]
  get 'legal', to: 'static_pages#legal_mentions'
  get 'donation', to: 'static_pages#donation'
  get 'about', to: 'static_pages#about'

  devise_for :users, :path => "/Mon_Profil"

  resources :users, except: [:new, :index, :create], path: "/Profil"
  resources :projects, :path => "/Projets" do
    resources :feats, except: [:index] ,:path => "/Feats"
  end
  resources :attachments, only: [:destroy]
  resources :likes, only: [:update]

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end

  namespace :admin do
    root to: 'static_pages#index'
    resources :users, except: [:new, :create]
    resources :projects, except: [:new, :create] do
      resources :feats, only: [:update, :destroy, :index]
    end
    resources :skills, except: [:show]
  end

end

app/models/user.rb
class User < ApplicationRecord
  after_create :welcome_send
  after_create :username_attribution

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/ }
  validates :user_name, presence: true, uniqueness: true, on: :update
  validates :social_link, 
  format: { with: /\A(?:(?:https?):\/\/)(?:\S+(?::\S*)?@)?(?:(?!10(?:\.\d{1,3}){3})(?!127(?:\.\d{1,3}){3})(?!169\.254(?:\.\d{1,3}){2})(?!192\.168(?:\.\d{1,3}){2})(?!172\.(?:1[6-9]|2\d|3[0-1])(?:\.\d{1,3}){2})(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])(?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}(?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))|(?:(?:[a-z\u00a1-\uffff0-9]+-?)*[a-z\u00a1-\uffff0-9]+)(?:\.(?:[a-z\u00a1-\uffff0-9]+-?)*[a-z\u00a1-\uffff0-9]+)*(?:\.(?:[a-z\u00a1-\uffff]{2,})))(?::\d{2,5})?(?:\/[^\s]*)?\z/i },
  allow_nil: true,
  allow_blank: true
  validates :avatar, 
    content_type: ['image/png', 'image/jpg', 'image/jpeg'],
    size: { less_than: 5.megabytes }

  has_many :projects, dependent: :destroy
  has_many :feats, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_and_belongs_to_many :skills
  has_one_attached :avatar
  
  private

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
  
  def username_attribution
    self.update(user_name: "Pseudo#{self.id }")
  end

end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < AdminController
    before_action :set_user, except: [:index]

    def index
      @users = User.order(:id)
    end

    def edit
    end

    def update
      if @user.update(user_params)
        flash[:success] = "L'utilisateur a bien été mis à jour."
        redirect_to admin_users_path
      else
        flash[:warning] = "Il y a eu un problème lors de la mise à jour de l'utilisateur"
        render 'edit'
      end
    end
    
    def destroy
      if @user.destroy
        flash[:success] = "L'utilisateur a bien été supprimé."
        redirect_to admin_users_path
      else
        flash[:warning] = "Il y a eu un problème lors de la suppression de l'utilisateur"
        redirect_to admin_users_path
      end
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :user_name, :social_link, :status)
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login
  before_action :set_user

  def show
  end

  def edit
  end

  def update
    if @user.update_attributes(users_params)
      flash[:success] = "Ton profil a bien été édité"
      redirect_to @user
    else
      flash[:warning] = "Il y a eu un problème lors de la modification de ton profil."
      render 'edit'
    end
  end

  def destroy
    @user.avatar.purge
    flash[:success] = 'Ton Avatar a bien été supprimé.'
    redirect_to @user
  end

  private
  
  def set_user
    @user = User.find(params[:id])
  end   

  def users_params
    params.require(:user).permit(:avatar, :user_name, :social_link, skill_ids: [])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% if @user.errors.any? %>
<%= render "shared/error_messages", object: @user %>
<% end %>

<div class="d-flex justify-content-center align-items-center text-center">
  <main class="col-lg-6">
    <h2><%= current_user.user_name %></h2>
    <%= form_with(model: @user, local: true, html: {class: "w-100"}) do |f| %> 
    <% if @user.avatar.attached? && @user.avatar.image?%>
    <div class= "field">
      <%= image_tag @user.avatar.variant(resize: "300x300"), class: "rounded-circle" %>
    </div>
    <% end %>

    <div class= "field my-3">
        <%= f.label "Change ton avatar" %><br />
        <%= f.file_field :avatar, autofocus: true, autocomplete: "avatar"  %>
    </div>

    <div class="field my-3">
        <%= f.label "Pseudo" %><br />
        <%= f.text_field  :user_name, autofocus: true, autocomplete: "pseudo" %>
    </div>       

    <div class="field my-3">
        <%= f.label "Lien réseau social" %><br />
        <%= f.text_field :social_link, autofocus: true, autocomplete: "social_link" %>
    </div>

    <div class="my-3 text-center" >
      <%= f.label "Tes points forts" %><br />
      <%= f.collection_check_boxes :skill_ids, Skill.all, :id, :name do |b| %>
      <%= b.label(:"data-value" => b.value, class: "m-1") { b.check_box + " " + b.text } %>
      <% end %>
    </div>

    <div class="actions m-2">
      <%= f.submit "Valider les modifications", class:" btn  btn-outline-secondary m-2" %> 
      <% if @user.avatar.attached? %>
      <%= link_to "Supprimer l'avatar", user_path, data: { method: :delete}, class: "btn btn-outline-danger m-2" %>  
      <% end %>     
      <%= link_to "Retour à l'accueil", projects_path, class:" btn  btn-outline-info m-2"  %>
    </div> 
    <% end %>
    <p><%= link_to 'Modifier mes identifiants de connexion', edit_user_registration_path, class: "btn btn-outline-warning m-3" %></p>   
  </main>
</div>

app/views/users/show.html.erb
<div class="container my-4">
  <div class="card bg-primary border-success">
    <div class="card-body">
      <h2 class="text-center m-4">Information de profil</h2>
      <div class="avatar-big m-auto avat-center">
        <% if @user.avatar.attached? %>
        <%= image_tag @user.avatar.variant(resize: "200x200"), class: "rounded-circle" %>
        <% else %>
        <%= image_tag 'default_avatar.png', class: "rounded-circle" %>
        <% end %>
      </div><br><hr>
      <table class="table table-borderless max-width-18 m-auto m-4">
        <tbody>
          <tr>
            <th scope="row", class="text-light">Pseudo:</th>
            <td class="text-secondary"><%=@user.user_name%></td>
          </tr>
          <tr>
            <th scope="row", class="text-light">Date:</th>
            <td class="text-secondary"><%= @user.created_at.strftime('Compte crée le :%e %b %Y') %></td>
          </tr>
          <% if @user.social_link? %>
          <tr>
            <th scope="row", class="text-light">Réseau social :</th>
            <td class="text-secondary"><%= link_to 'lien réseau social', @user.social_link, target: :_blank %></td>
          </tr>
          <% end %>
          <tr>
            <th scope="row", class="text-light">Mes points forts :</th>
            <td><% @user.skills.each do |skill| %>
              <span class='badge rounded-pill bg-success'><%= skill.name %></span>
            <% end %>
            </td>
          </tr>
          <tr>
          <th scope="col", class="text-light"> Projets:</th>
            <ul>
              <td class="text-secondary"><% @user.projects.each do |project| %>
              <li><%= link_to project.title, project_path(project) %></li>
              <% end %>
              </td>
            <ul>
          </tr>
          <tr>
            <th scope="col", class="text-light"> Feats:</th>
            <ul>
              <td class="text-secondary"><% @user.feats.each do |feat| %>
                <li><%= link_to feat.title, project_path(feat.project) %></li>
              <% end %></td>
            </ul>
          </tr>
        </tbody>
      </table><br><hr>
      <div class="actions text-center m-4">
        <% if @user == current_user %>
        <%= link_to 'Modifier mon profil', edit_user_path,class:" btn  btn-outline-warning m-2" %>
        <% end %>
      </div>
    </div>
  </div>
</div>