config/routes.rb
Rails.application.routes.draw do
  
  root 'projects#index'
  
  resources :static_pages, only: [:create]
  get 'legal', to: 'static_pages#legal_mentions'
  get 'donation', to: 'static_pages#donation'
  get 'about', to: 'static_pages#about'

  devise_for :users, :path => "/Mon_Profil"

  resources :users, except: [:new, :index, :create], path: "/Profil"
  resources :projects, :path => "/Projets" do
    resources :feats, except: [:index] ,:path => "/Feats"
  end
  resources :attachments, only: [:destroy]
  resources :likes, only: [:update]

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end

  namespace :admin do
    root to: 'static_pages#index'
    resources :users, except: [:new, :create]
    resources :projects, except: [:new, :create] do
      resources :feats, only: [:update, :destroy, :index]
    end
    resources :skills, except: [:show]
  end

end

app/models/project.rb
class Project < ApplicationRecord
  after_create :create_project_email_send
  before_destroy :purge_all_attachments

  has_many :feats, dependent: :destroy
  has_many_attached :attachments, dependent: :destroy
  has_one_attached :picture
  belongs_to :user
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :likers, through: :likes, source: :user
  has_many :featers, through: :feats, source: :user
  has_and_belongs_to_many :skills
 

  validates :title, presence: true, length: { in: 5..150 }
  validates :description, presence: true, length: { in: 5..3000 }
  validates :picture, 
    content_type: ['image/png', 'image/jpg', 'image/jpeg'],
    size: { less_than: 5.megabytes }
  validates :attachments, 
    size: { less_than: 20.megabytes },
    content_type: ['image/png', 'image/jpg', 'image/jpeg',
                   'audio/x-wav', 'audio/mpeg',
                   'video/mp4',
                   'text/plain']

  private

  def create_project_email_send
    UserMailer.create_project_email(self).deliver_now
  end
end

app/controllers/admin/projects_controller.rb
module Admin
  class ProjectsController < ApplicationController
    before_action :set_project, except: [:index]

    def index
      @projects = Project.all.order(id: :desc)
    end

    def show
    end
    
    def edit
    end

    def update
      if @project.update_attributes(project_params)
        flash[:success] = "Le projet a bien été édité"
        redirect_to edit_admin_project_path(@project)
      else
        flash[:warning] = "Il y a eu un problème lors de la modification du projet."
        render 'edit'
      end
    end
    
    def destroy
      if @project.destroy
        flash[:success] = 'Le projet a bien été supprimé.'
        redirect_to admin_projects_path
      else
        flash[:warning] = 'Il y a eu un problème lors de la suppression du projet.'
        redirect_to @project
      end
    end

    private

    def project_params
      params.require(:project).permit(:title, :description, :picture, attachments: [], skill_ids: [])
    end

    def set_project
      @project = Project.find(params[:id])
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_login, except: [:index]
  before_action :set_project, except: [:index, :new, :create]
  before_action :ownership_verification, only: [:edit, :update, :destroy]

  def index
    @sort_types_list = { last_created: "derniers crées",
                         popularity: "popularité",
                         common_skills: "compétences communes", 
                         liked: "projets aimés", 
                         feated: "tes feats" }
    @projects = projects_sorted_by(params[:sort_type])
    if params[:sort_type].nil?
      @sort_type = @sort_types_list[:last_created]
    else
      @sort_type = @sort_types_list[params[:sort_type].to_sym]
    end
  end

  def show
    @feat = Feat.new
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    if @project.save
      flash[:success] = "Ton projet a bien été publié !"
      redirect_to @project
    else
      flash[:warning] = "Il y eu un problème lors de la création de ton projet."
      render 'new'
    end
  end

  def edit
  end

  def update
    if @project.update_attributes(project_params)
      flash[:success] = "Ton projet a bien été édité"
      redirect_to @project
    else
      flash[:warning] = "Il y a eu un problème lors de la modification de ton projet."
      render 'edit'
    end
  end
  
  def destroy
    if @project.destroy
      flash[:success] = 'Ton projet a bien été supprimé.'
      redirect_to root_path
    else
      flash[:warning] = 'Il y a eu un problème lors de la suppression de ton projet.'
      redirect_to @project
    end
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :picture, attachments: [], skill_ids: [])
  end

  def set_project
    @project = Project.find(params[:id])
  end

  def ownership_verification
    unless @project.user == current_user
      flash[:danger] = "L'accès à cette page est restreint."
      redirect_to root_path
    end
  end

  def projects_sorted_by(type)
    case type
    when "popularity"
      Project.all.sort_by { |project| project.likes.count }.reverse
    when "last_created"
      Project.all.order(created_at: :desc)
    when "common_skills"
      interest = []
      current_user.skills.each do |user_skill|
        Project.all.each do |project|
          interest << project if project.skills.include?(user_skill)
        end
      end
      interest.uniq
    when "liked"
      Project.all.select { |project| project.likers.include?(current_user) }
    when "feated"
      Project.all.select { |project| project.featers.include?(current_user) }
    else
      Project.all.order(created_at: :desc)
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/projects/edit.html.erb
<% if @project.errors.any? %>
<%= render "shared/error_messages", object: @project %>
<% end %>

<div class="container">
  <h2>Edition du projet</h2>
  <%= link_to 'Retour', admin_projects_path, class: 'btn btn-info btn-sm' %>

  <%= form_for ([:admin, @project]) do |f| %>
  <div class="card col-lg-6 mx-auto">
    <%= image_tag @project.picture, alt: @project.title, class: "card-img-top" if @project.picture.attached? %>
    <div class="card-body">
      <div class="text-muted">
        <%= "ID : #{@project.id}" %><br />
        <%= "Crée le #{@project.created_at.strftime('%e %b %Y à %H:%M:%S')}" %><br />
        <%= "Dernière modification le #{@project.updated_at.strftime('%e %b %Y à %H:%M:%S')}" %><br />
        <%= link_to "#{@project.feats.count} Feats", admin_project_feats_path(project_id: @project), class: "text-muted" %>
      </div>
      <%= label_tag 'Titre' %><br />
      <%= f.text_field :title %><br />

      <%= label_tag 'Description' %><br />
      <%= f.text_area :description, rows: "10", cols: "30" %><br />

      <%= f.label "Ajouter des pièces jointes" %><br />
      <%= f.file_field :attachments, multiple: true %><br />

      <%= label_tag "Modifier l'image d'illustration" %><br />
      <%= f.file_field :picture %><br />

      <button type="submit" class="btn btn-primary mt-3">Modifier</button>

    </div>
  </div>
  <% end %>
  <div class="card col-lg-6 mx-auto">
    <h2>Fichiers joints au projet</h2>
    <% @project.attachments.each do |attachment| %>
    <% unless attachment.id == nil %>
    <%= image_tag attachment, class: "card-img-top" %>
    <%= attachment.filename %>
    <%= link_to "Supprimer", attachment_path(attachment), data: { method: :delete, confirm: "Est tu sûr de vouloir supprimer ce fichier ?" }, class: "btn btn-danger my-2" %>
    <% end %>
    <% end %>
    </div>
  </div>

</div>

app/views/admin/projects/index.html.erb
<div class="container">
  <h2>Projets en base de donnée</h2>
  <%= link_to 'Accueil Admin', admin_root_path, class: 'btn btn-info mb-1' %>


  <table class="table table-hover table-sm bg-white">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Titre</th>
        <th scope="col">Créateur</th>
        <th scope="col">Crée le</th>
        <th scope="col">Feats</th>
        <th scope="col">Likes</th>
      </tr>
    </thead>
    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <th><%= project.id %></th>
          <th><%= project.title %></th>
          <th><%= project.user.user_name + "(##{project.user.id})" %></th>
          <th><%= project.created_at.strftime('%e %b %Y') %></th>
          <th><%= project.feats.count %></th>
          <th><%= project.likers.count %></th>
          <th><%= link_to 'Afficher/Editer', edit_admin_project_path(project), class: 'btn btn-secondary btn-sm' %></th>
          <th><%= link_to 'Supprimer', admin_project_path(project), data: { method: :delete, confirm: "Est tu sûr de vouloir supprimer ce projet ?" }, class: 'btn btn-danger btn-sm'%></th>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>