config/routes.rb
Rails.application.routes.draw do
  
  root 'projects#index'
  
  resources :static_pages, only: [:create]
  get 'legal', to: 'static_pages#legal_mentions'
  get 'donation', to: 'static_pages#donation'
  get 'about', to: 'static_pages#about'

  devise_for :users, :path => "/Mon_Profil"

  resources :users, except: [:new, :index, :create], path: "/Profil"
  resources :projects, :path => "/Projets" do
    resources :feats, except: [:index] ,:path => "/Feats"
  end
  resources :attachments, only: [:destroy]
  resources :likes, only: [:update]

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end

  namespace :admin do
    root to: 'static_pages#index'
    resources :users, except: [:new, :create]
    resources :projects, except: [:new, :create] do
      resources :feats, only: [:update, :destroy, :index]
    end
    resources :skills, except: [:show]
  end

end

app/models/project.rb
class Project < ApplicationRecord
  after_create :create_project_email_send
  before_destroy :purge_all_attachments

  has_many :feats, dependent: :destroy
  has_many_attached :attachments, dependent: :destroy
  has_one_attached :picture
  belongs_to :user
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :likers, through: :likes, source: :user
  has_many :featers, through: :feats, source: :user
  has_and_belongs_to_many :skills
 

  validates :title, presence: true, length: { in: 5..150 }
  validates :description, presence: true, length: { in: 5..3000 }
  validates :picture, 
    content_type: ['image/png', 'image/jpg', 'image/jpeg'],
    size: { less_than: 5.megabytes }
  validates :attachments, 
    size: { less_than: 20.megabytes },
    content_type: ['image/png', 'image/jpg', 'image/jpeg',
                   'audio/x-wav', 'audio/mpeg',
                   'video/mp4',
                   'text/plain']

  private

  def create_project_email_send
    UserMailer.create_project_email(self).deliver_now
  end
end

app/controllers/admin/projects_controller.rb
module Admin
  class ProjectsController < ApplicationController
    before_action :set_project, except: [:index]

    def index
      @projects = Project.all.order(id: :desc)
    end

    def show
    end
    
    def edit
    end

    def update
      if @project.update_attributes(project_params)
        flash[:success] = "Le projet a bien été édité"
        redirect_to edit_admin_project_path(@project)
      else
        flash[:warning] = "Il y a eu un problème lors de la modification du projet."
        render 'edit'
      end
    end
    
    def destroy
      if @project.destroy
        flash[:success] = 'Le projet a bien été supprimé.'
        redirect_to admin_projects_path
      else
        flash[:warning] = 'Il y a eu un problème lors de la suppression du projet.'
        redirect_to @project
      end
    end

    private

    def project_params
      params.require(:project).permit(:title, :description, :picture, attachments: [], skill_ids: [])
    end

    def set_project
      @project = Project.find(params[:id])
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_login, except: [:index]
  before_action :set_project, except: [:index, :new, :create]
  before_action :ownership_verification, only: [:edit, :update, :destroy]

  def index
    @sort_types_list = { last_created: "derniers crées",
                         popularity: "popularité",
                         common_skills: "compétences communes", 
                         liked: "projets aimés", 
                         feated: "tes feats" }
    @projects = projects_sorted_by(params[:sort_type])
    if params[:sort_type].nil?
      @sort_type = @sort_types_list[:last_created]
    else
      @sort_type = @sort_types_list[params[:sort_type].to_sym]
    end
  end

  def show
    @feat = Feat.new
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    if @project.save
      flash[:success] = "Ton projet a bien été publié !"
      redirect_to @project
    else
      flash[:warning] = "Il y eu un problème lors de la création de ton projet."
      render 'new'
    end
  end

  def edit
  end

  def update
    if @project.update_attributes(project_params)
      flash[:success] = "Ton projet a bien été édité"
      redirect_to @project
    else
      flash[:warning] = "Il y a eu un problème lors de la modification de ton projet."
      render 'edit'
    end
  end
  
  def destroy
    if @project.destroy
      flash[:success] = 'Ton projet a bien été supprimé.'
      redirect_to root_path
    else
      flash[:warning] = 'Il y a eu un problème lors de la suppression de ton projet.'
      redirect_to @project
    end
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :picture, attachments: [], skill_ids: [])
  end

  def set_project
    @project = Project.find(params[:id])
  end

  def ownership_verification
    unless @project.user == current_user
      flash[:danger] = "L'accès à cette page est restreint."
      redirect_to root_path
    end
  end

  def projects_sorted_by(type)
    case type
    when "popularity"
      Project.all.sort_by { |project| project.likes.count }.reverse
    when "last_created"
      Project.all.order(created_at: :desc)
    when "common_skills"
      interest = []
      current_user.skills.each do |user_skill|
        Project.all.each do |project|
          interest << project if project.skills.include?(user_skill)
        end
      end
      interest.uniq
    when "liked"
      Project.all.select { |project| project.likers.include?(current_user) }
    when "feated"
      Project.all.select { |project| project.featers.include?(current_user) }
    else
      Project.all.order(created_at: :desc)
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true, html: {class: "w-100"}) do |f| %>

<div class="form-floating mt-2 ">
  <div class="field mb-2 ">
    <%= f.label 'Titre' %><br />
    <%= f.text_field :title, required: true, id:"text_input_for_project" %><br />
  </div>
</div>

<div class="form-floating mt-2 ">
  <div class="field mb-2 ">
    <%= f.label 'Description' %><br />
    <%= f.text_area :description, required: true, id:"text_input_for_project" %><br />
  </div>
</div>

<div class="form-floating mt-3">
  <div class="field mb-2"><br />
    <%= f.label "Image d'illustration de ton projet", class:"mb-2" %><br />
    <%= f.file_field :picture %><br />
  </div>
</div>

<div class="my-3 text-center" >
  <%= f.label "Quelles compétences cherchez-tu ?", class: "mb-2" %><br />
  <%= f.collection_check_boxes :skill_ids, Skill.all, :id, :name do |b| %>
  <%= b.label(:"data-value" => b.value, class: "m-1") { b.check_box + " " + b.text } %>
  <% end %>
</div>

<div class="form-floating mt-3">
  <div class="field mb-2"><br />
    <%= f.label "Fichiers Joints", class:"mb-2" %><br />
    <%= f.file_field :attachments, multiple: true %><br />
  </div>
</div>

<div class="form-floating mt-2">
  <div class="field mb-2"><br />
    <%= f.submit "Envoyer", class:"btn btn-secondary px-4"%><br />
  </div>
</div>

<% end %>

app/views/projects/edit.html.erb
<% if @project.errors.any? %>
<%= render "shared/error_messages", object: @project %>
<% end %>

<div class="d-flex flex-column justify-content-center align-items-center text-center">
  <div class="col-lg-6">
    <h1>Modifie ton projet</h1>

    <%= render 'form', project: @project %>

    <h3>Fichiers liés à ce projet</h3>

    <%= render "shared/attachments_display", source_object: @project, deletion_possibility: true %>
    
  </div>
</div>

app/views/projects/index.html.erb
<%= render "layouts/carousel"%>
<% if user_signed_in? %>
<div style="border-top: 1px solid #ecc93c;margin: 20px 0;"></div>
  <div class="d-flex justify-content-center align-items-center">
    <div class="dropdown">
      Afficher les projets par
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        <%= @sort_type %>
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        <% @sort_types_list.each do |sort_type, name| %>
        <li><%= link_to name, projects_path(sort_type: sort_type), class: "dropdown-item" %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div style="border-top: 1px solid #ecc93c;margin: 20px 0;"></div>
  <div class="container">   
    <% if @projects.empty? %>
      <h5>Il n'y a pas de résultat à afficher... Lance ton propre projet <%= link_to "par ici", new_project_path %> !</h5>
    <% end %>  
    <% @projects.each do |project| %>
    <div class="col-12 d-flex one-card-custom">
      <% if project.picture.attached? %>
        <%= image_tag project.picture.variant(resize: "400x400"),alt:"#{project.title}", class:"col-lg-3 col-md-12 m-2", style:"border-radius:30px;" %>
      <% else %>
        <%= image_tag 'default.jpg',alt:"#{project.title}", class:"col-lg-3 col-md-12 m-2", style:"border-radius:30px;"%>
      <% end %>   
      <div class="card w-75 mx-1 my-2 bg-primary border-success">
        <div class="card-header bg-primary border-success d-flex justify-content-between align-items-center">
          <h5><%= project.title %></h5>
            <p class="text-muted"><em>Publié le <%= project.created_at.strftime('%e %b %Y')%></em></p>
            <p class="text-muted"><em>Par <%= link_to project.user.user_name, user_path(project.user)%></em></p>
        </div>
        <div class="card-body bg-primary d-flex flex-column justify-content-around">
          <div class="mb-1 text-muted">
            <% project.skills.each do |skill| %>
            <span class='badge rounded-pill  mx-1'><%= skill.name %></span>
            <% end %>
          </div>
          <p class="text-truncate card-text"><%= project.description %></p>
          <div class="d-flex justify-content-around">
            <% if project.feats.count < 1 %>
                <p><em>Pas de feats sur ce projet</em></p>
            <% elsif project.feats.count == 1 %>
                <p><em>1 feat sur ce projet</em></p>
            <% else %>
                <p><em><%= project.feats.count%> feats sur ce projet</em></p>
            <% end %>
            <a id="<%= "star_icon_project#{project.id}" %>" href="<%= like_path(likeable: "project", id: project.id) %>" data-method='patch' data-remote='true' class="btn btn-<%= current_user_has_liked?(project) ? "warning" : "primary" %> primary">
                <i class="far fa-star"></i>
                <span id ="<%= "star_counter_project#{project.id}" %>"><%= project.likes.count %></span>
            </a>
            <%= link_to "détails du projet", project_path(project.id), class:"btn btn-success" %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
</div>
<% else %>

<div style="border-top: 1px solid #ecc93c;margin: 20px 0;"></div>
<section class="showcase">
    <div class="container-fluid p-0">
        <div class="d-flex img_for_presente">
            <%= image_tag 'instruments.png',alt:"", class:"col-lg-6 order-lg-2 text-white showcase-img", width: "50%"%>
            <div class="col-lg-6 order-lg-1 my-auto showcase-text">
                <h1>Première plateforme d'entraide créative</h1>
                <p class="lead mb-0">Match & Feat est LE lieu de rencontre artistique pour collaboration musicale ! Notre plateforme héberge de nombreux projets "en quête de devenir" et 100% libres de droits.<br />Ils sont inachevés ou ont été postés volontairement à un stade laissant libre cours à la créativité musicale de chacun. L'entraide, le partage, la créativité et la bienveillance sont les maitres mots !</p>
            </div>
        </div>
        <div class="d-flex img_for_presente">
            <%= image_tag 'guitar.jpg',alt:"", class:"col-lg-6 text-white showcase-img", width: "50%"%>
            <div class="col-lg-6 my-auto showcase-text">
                <h1>Mets en lumière ton projet</h1>
                <p class="lead mb-0">Match&feat est la plateforme idéale pour montrer ton projet au monde entier ! Que tu ais une oeuvre incomplète, un manque d'inspiration ou alors que tu souhaites donner libre court à la créativité des membres, nous sommes là pour toi !<br />Après ton inscription, tu pourras proposer ta maquête, elle sera à disposition de tous nos membres qui pourront venir proposer leur contribution. N'attends plus et laisse la magie opérer !</p>
            </div>
        </div>
        <div class="d-flex img_for_presente">
            <%= image_tag 'neon.png',alt:"", class:"col-lg-6 order-lg-2 text-white showcase-img", width: "50%"%>
            <div class="col-lg-6 order-lg-1 my-auto showcase-text">
                <h1>Mets en lumière ton talent</h1>
                <p class="lead mb-0">Parcours les nombreux projets inspirants et captivants que nous hébergeons puis apporte ta contribution !<br />Parce que nous pensons que chaque talent doit pouvoir s'exprimer librement et gratuitement, match&feat est la plateforme idéale pour faire connaître ta patte musicale au monde entier !</p>
            </div>
        </div>
    </div>
</section>

<div style="border-top: 1px solid #ecc93c;margin: 20px 0;"></div>
<div class="d-flex flex-column align-items-center">
  <h3><%= link_to "S'inscrire", new_user_registration_path, class: "nav-link " %></h3>
  <p>N'attends plus et rejoins la communauté !</p>
</div>

<div style="border-top: 1px solid #ecc93c;margin: 20px 0;"></div>
<section class="testimonials text-center">
    <div class="container">
        <h2 class="mb-5">Qui se cache derrière</h2>
        <div class="d-flex justify-content-center flex-wrap">
            <div class="col-lg-2 m-2">
                <div href="#" class="testimonial-item mx-auto mb-5 mb-lg-0">
                    <%= image_tag 'team_flo.jpg',alt:"", class:"img-fluid rounded-circle mb-3" %>
                    <h5>Flo</h5>
                    <p class=" mb-0">"Il est le fils spirituel de Gary McKinnon !"</p>
                </div>
            </div>
            <div class="col-lg-2 m-2">
                <div class="testimonial-item mx-auto mb-5 mb-lg-0">
                    <%= image_tag 'team_hary.jpg',alt:"", class:"img-fluid rounded-circle mb-3" %>
                    <h5>Hary</h5>
                    <p class=" mb-0">"Le cerveau de l'ombre à l'origine du projet."</p>
                </div>
            </div>
            <div class="col-lg-2 m-2">
                <div class="testimonial-item mx-auto mb-5 mb-lg-0">
                    <%= image_tag 'team_kevin.jpg',alt:"", class:"img-fluid rounded-circle mb-3" %>
                    <h5>Kevin</h5>
                    <p class=" mb-0">"N'est pas grand chose sans Florent!"</p>
                </div>
            </div>
            <div class="col-lg-2 m-2">
                <div class="testimonial-item mx-auto mb-5 mb-lg-0">
                    <%= image_tag 'team_jo.jpg',alt:"", class:"img-fluid rounded-circle mb-3" %>
                    <h5>Joffrey</h5>
                    <p class=" mb-0">"Un foutu opportuniste qui espère toucher le pactole lors du rachat par Google ou Meta!"</p>
                </div>
            </div>
            <div class="col-lg-2 m-2">
                <div class="testimonial-item mx-auto mb-5 mb-lg-0">
                    <%= image_tag 'team_lucas.jpg',alt:"", class:"img-fluid rounded-circle mb-3" %>
                    <h5>Lucas</h5>
                    <p class=" mb-0">"Un demi-dieu de la manipulation des images"</p>
                </div>
            </div>
        </div>
    </div>
</section>

<% end %>

app/views/projects/new.html.erb
<% if @project.errors.any? %>
<%= render "shared/error_messages", object: @project %>
<% end %>

<div class="d-flex flex-column justify-content-center align-items-center text-center">  
  <div class="col-lg-6">
    <i class="fas fa-tasks" style="font-size:60px"></i>
    <br>
    <h1>Créer un nouveau projet</h1>
    <%= render 'form', project: @project %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="container my-4">
  <div class="card bg-primary border-success">

    <a id="<%= "star_icon_project#{@project.id}" %>" href="<%= like_path(likeable: "project") %>" data-method='patch' data-remote='true' class="btn btn-<%= current_user_has_liked?(@project) ? "warning" : "primary" %> primary position-absolute top-0 start-0 fs-2">
      <i class="far fa-star"></i>
      <span id ="<%= "star_counter_project#{@project.id}" %>" class="position-absolute top-0 start-0 translate-middle badge rounded-pill bg-info fs-6">
        <%= @project.likes.count %>
        <span class="visually-hidden">Aime ça !</span>
      </span>
    </a>

    <div class="row g-0">
      <div class="col-md-4 mb-0">
        <% if @project.picture.attached? %>
        <%= image_tag @project.picture.variant(resize: "600x600"),alt:"#{@project.title}", class:"img-fluid rounded-start w-100" %>
        <% else %>
        <%= image_tag 'default.jpg',alt:"#{@project.title}", class:"img-fluid rounded-start w-100" %>
        <% end %>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h3 class="card-title"><%= @project.title %></h3>
          <p class="card-text"><small class="text-muted">Crée le : <%= @project.created_at.strftime('%e %b %Y')%> par <%=link_to @project.user.user_name, user_path(@project.user) %></small></p>
          <% if @project.user == current_user %>
          <%= link_to "Modifier", edit_project_path(@project),class:"link-modify fs-6" %>
          <%= link_to "Supprimer", project_path(@project), data: { method: :delete, confirm: "Est tu sûr de vouloir supprimer votre collaboration ?" }, class:"link-delete fs-6" %>
          <% end%>
          <p class="card-text"><%= @project.description %></p>
          <% @project.skills.each do |skill| %>
          <span class='badge rounded-pill bg-success'><%= skill.name %></span>
          <% end %>
        </div>
      </div>
    </div>

    <hr>
    <h3 class="text-center">Fichiers liés à ce projet</h3>

    <%= render "shared/attachments_display", source_object: @project, deletion_possibility: false %>

    <hr>
    <h3 class="text-center">Feats</h3>

    <div class="field d-flex flex-column align-items-center justify-content-center">
      <%= form_for([@project, @feat], class:"bg-primary w-100", :method => "post") do |f| %>
      <div class="form-card-page form-floating d-flex flex-column mt-2">
        <%= f.text_field :title, placeholder: "Que veux tu apporter ? "%>
        <%= f.text_area :description, placeholder: "Description du feat...", class:'my-2', required: true %><br />
        <%= f.file_field :attachments, multiple: true, class: "my-3" %>
        <%= submit_tag "Je contribue", class:'btn btn-secondary m-2' %>
      </div>
      <% end %>
    </div>
    <% if @project.feats.count < 1 %>
    <p>Aucun feat pour le moment... À toi de jouer !</p>
    <% end %>
    <% @project.feats.each do |feat| %>
    <div class="card bg-primary border-top">
      <div class="card-header">
        <h4><%= feat.title %></h4>
        <div class="text-muted small">Posté le : <%= feat.created_at.strftime('%e %b %Y')%> par <%= link_to feat.user.user_name, user_path(feat.user) %></div>
        <% if feat.user == current_user %>
        <%= link_to "Modifier", edit_project_feat_path(@project, feat),class:"link-modify fs-6" %>
        <%= link_to "Supprimer", project_feat_path(@project, feat), data: { method: :delete, confirm: "Est tu sûr de vouloir supprimer ta contribution ?" }, class:"link-delete fs-6" %>
        <% end%>
      </div>
      <div class="card-body">
        <p class="card-text"><%= feat.description %></p>
        <a href="<%= like_path(likeable: "feat", id: feat) %>" data-method='patch' data-remote='true' class="btn btn-primary">
          <span id="like_counter_feat_<%= feat.id %>"><%= feat.likers.count %></span>
          <i id="like_icon_feat_<%= feat.id %>" class="fa<%= current_user_has_liked?(feat) ? "s" : "r" %> fa-heart"></i>
        </a>
      </div>
      <div class="card-footer text-muted">
        <%= feat.attachments.count %> Fichiers liés : <% feat.attachments.each do |attachment| %>
        <%= link_to attachment.filename, rails_blob_path(attachment, disposition: "attachment") %>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>